env: prod
app:
  port: 6060

cors:
  allowed-origins: '*'
  allow-methods: POST,GET,OPTIONS
  allow-headers: Authorization, Content-Type, Accept-Encoding, User-Agent, Accept
  max-age: 86400

data-source:
  url: root:123456@tcp(123.57.237.176:3306)/gomailer

re-captcha-secret: 6Ld2jeMUAAAAAJ_9NsYfI1xqzieIgxOFzb8aPUOa